{
    "Bulgaria" : ["Carte de Identitate, Pașaport", "https://www.mae.ro/travel-conditions/3677", "Cetățenii români nu au nevoie de viză pentru a călători în Bulgaria, ci doar de cartea de identitate sau de pașaport, aflate în termen de valabilitate."],
    "Republica Cehă" : ["Carte de Identitate, Pașaport", "https://www.mae.ro/travel-conditions/3679", "Cetățenii români nu au nevoie de viză pentru a călători în Republica Cehă. Intrarea este permisă cu cartea de identitate sau cu pașaportul, valabile pentru o perioadă de cel puțin 3 luni. Perioada maximă de ședere este de 3 luni, fiind necesară obținerea unui permis de ședere pentru perioade mai lungi. Mai multe informații pe site-ul oficial MAE."],
    "Ungaria" : ["Carte de Identitate, Pașaport", "https://www.mae.ro/travel-conditions/3756", "Cetățenii români nu au nevoie de viză pentru a călători în Ungaria, ci doar de cartea de identitate sau de pașaport, aflate în termen de valabilitate."],
    "Franța" : ["Carte de Identitate, Pașaport", "https://www.mae.ro/travel-conditions/3698", "Cetățenii români nu au nevoie de viză pentru a călători în Franța, ci doar de cartea de identitate sau de pașaport, aflate în termen de valabilitate."],
    "Germania" : ["Carte de Identitate, Pașaport", "https://www.mae.ro/travel-conditions/3700", "Cetățenii români nu au nevoie de viză pentru a călători în Germania, ci doar de cartea de identitate sau de pașaport, aflate în termen de valabilitate."],
    "Italia" : ["Carte de Identitate, Pașaport", "https://www.mae.ro/travel-conditions/3711", "Cetățenii români nu au nevoie de viză pentru a călători în Italia, ci doar de cartea de identitate sau de pașaport, aflate în termen de valabilitate."],
    "Polonia" : ["Carte de Identitate, Pașaport", "https://www.mae.ro/travel-conditions/3735", "Cetățenii români nu au nevoie de viză pentru a călători în Polonia, ci doar de cartea de identitate sau de pașaport, aflate în termen de valabilitate. Pentru o perioadă mai mare de 3 luni, este necesară înregistrarea la Oficiul pentru Străini (Urząd ds. Cudzoziemców) al fiecărei regiuni (voievodat) și obținerea adeverinței privind înregistrarea șederii cetățeanului UE. Mai multe informații pe site-ul oficial MAE."],
    "Spania" : ["Carte de Identitate, Pașaport", "https://www.mae.ro/travel-conditions/3747", "Cetățenii români nu au nevoie de viză pentru a călători în Spania, ci doar de cartea de identitate sau de pașaport, aflate în termen de valabilitate."],
    "Olanda" : ["Carte de Identitate, Pașaport", "https://haga.mae.ro/node/177", "Cetățenii români nu au nevoie de viză pentru a călători în Olanda, ci doar de cartea de identitate sau de pașaport, aflate în termen de valabilitate. Este important de menționat faptul că poliția, controlorii de bilete, inspectorii de muncă, furnizorii de servicii medicale sau alte oficialități vă pot solicita identificareae. Conform legii, sunteți obligat să aveți asupra dumneavoastră în orice moment un document de identitate valabil în original, lipsa acestuia pedepsindu-se cu o amendă de 60 EUR."],
    "Grecia" : ["Carte de Identitate, Pașaport", "https://www.mae.ro/travel-conditions/3701", "Cetățenii români nu au nevoie de viză pentru a călători în Grecia, ci doar de cartea de identitate sau de pașaport, aflate în termen de valabilitate."],
    "Croația" : ["Carte de Identitate, Pașaport", "https://www.mae.ro/travel-conditions/3688", "Cetățenii români nu au nevoie de viză pentru a călători în Croația, ci doar de cartea de identitate sau de pașaport, aflate în termen de valabilitate. Este important de menționat faptul că cetățenii români care doresc să rămână în Croația pentru perioade mai lungi de 90 de zile trebuie să se înregistreze, în funcție de scopul șederii, la autoritățile croate competente. Mai multe informații pe site-ul oficial MAE."],
    "Danemarca" : "Carte de Identitate, Pașaport"
    "Irlanda" : "Carte de Identitate, Pașaport"
    "Portugalia" : "Carte de Identitate, Pașaport"
    "Belgia" : "Carte de Identitate, Pașaport"
    "Austria" : "Carte de Identitate, Pașaport"
    "Finlanda" : "Carte de Identitate, Pașaport"
    "Cipru" : "Carte de Identitate, Pașaport"
    "Luxemburg" : "Carte de Identitate, Pașaport"
    "Lituania" : "Carte de Identitate, Pașaport"
    "Slovenia" : "Carte de Identitate, Pașaport"
    "Malta" : "Carte de Identitate, Pașaport"
    "Slovacia" : "Carte de Identitate, Pașaport"
    "Letonia" : "Carte de Identitate, Pașaport"
    "Estonia" : "Carte de Identitate, Pașaport"
    "Suedia" : "Carte de Identitate, Pașaport"
    "Rusia"
    "Ucraina" : ["Pașaport", "https://www.mae.ro/travel-conditions/3755", "Cetățenii români nu au nevoie de viză de intrare în Ucraina pentru călătorii de scurtă durată, maximul fiind de 90 de zile. Așadar, cetățenii români pot intra pe teritoriul Ucrainei cu un pașaport valabil minimum 90 de zile. Totodată, străinii trebuie să demonstreze Poliției de Frontieră că dețin resursele financiare necesare pe durata șederii în Ucraina. Summa necesară este de aproximativ 2000 EUR/lună, respectiv 400 EUR/săptămână sau echivalentul în orice altă valută. Mai multe informații pe site-ul oficial MAE."],
    "Norvegia"
    "Regatul Unit al Marii Britanii"
    "Belarus"
    "Kazakhstan"
    "Islanda"
    "Serbia" : ["Carte de Identitate, Pașaport", "https://www.mae.ro/travel-conditions/3742", "Cetățenii români nu au nevoie de viză de intrare în Serbia pentru călătorii de scurtă durată, maximul fiind de 90 de zile. Accesul pe teritoriul Serbiei se poate face pe baza cărții de identitate sau a unui pașaport temporar. Totodată, cetățenii străini trebuie să facă dovada mijloacelor suficiente de întreținere pe durata șederii în acest stat și pentru returnarea în țara de origine sau pentru continuarea călătoriei, precum și a existenței unei asigurări medicale de călătorie valabile pe durata șederii în Serbia, respectiv a tranzitării acestei țări. Mai multe informații pe site-ul oficial MAE."],
    "Bosnia și Herțegovina"
    "Elveția"
    "Moldova"
    "Armenia"
    "Albania"
    "Macedonia de Nord"
    "Turcia"
    "Muntenegru"
    "Kosovo"
    "Azerbaijan"
    "Georgia"
    "Andora"
    "Liechtenstein"
    "San Marino"
    "Monaco"
    "Vatican"
    "Statele Unite ale Americii"
    "Nigeria"
    "Etiopia"
    "Egipt"
    "Republica Democrată Congo"
    "Tanzania"
    "Africa de Sud"
    "Kenya"
    "Uganda"
    "Algeria"
    "Sudan"
    "Maroc"
    "Mozambic"
    "Ghana"
    "Angola"
    "Somalia"
    "Coasta de Fildeș"
    "Madagascar"
    "Camerun"
    "Burkina Faso"
    "Niger"
    "Malawi"
    "Zambia"
    "Mali"
    "Senegal"
    "Zimbabwe"
    "Ciad"
    "Tunisia"
    "Guinea"
    "Ruanda"
    "Benin"
    "Burundi"
    "Sudanul de Sud"
    "Eritrea"
    "Sierra Leone"
    "Togo"
    "Libia"
    "Republica Centrafricană"
    "Mauritania"
    "Republica Congo"
    "Liberia"
    "Namibia"
    "Botswana"
    "Lesotho"
    "Gambia"
    "Gabon"
    "Guinea-Bissau"
    "Mauritius"
    "Guinea Ecuatorială"
    "Eswatini"
    "Dijbouti"
    "Reunion (Franța)"
    "Comoros"
    "Capul Verde"
    "Mayotte (Franța)"
    "Sao Tome and Principe"
    "Seychelles"
    "Saint Helena, Ascension and Tristan da Cunha"
    "China"
    "India"
    "Arabia Saudită"
    "Iran"
    "Mongolia"
    "Indonezia"
    "Pakistan"
    "Myanmar"
    "Afghanistan"
    "Yemen"
    "Thailanda"
    "Turkmenistan"
    "Uzbekistan"
    "Irak" ["Document de călătorie, Viză", "https://www.mae.ro/travel-conditions/3706", "Cetățenii români care doresc să călătorească în Republica Irak trebuie să dețină un document de călătorie cu o valabilitatet mai mare de 6 luni, precum și de viză ce poate fi obținută de la Ambasada Republicii Irak la București. Este extrem de important de menționat faptul că Ministerul Afacerilor externe recomandă prudență sau chiar evitarea călătoriilor în Irak, situația de securitate din această țară fiind grav afectată zilnic de acțiuni cu caracter terorist. Mai multe informații pe site-ul oficical MAE."],
    "Japonia"
    "Vietnam"
    "Malaezia"
    "Oman"
    "Filipine"
    "Laos"
    "Kyrgystan"
    "Siria"
    "Cambodgia"
    "Bangladesh"
    "Nepal"
    "Tajikistan"
    "Coreea de Nord" ["Document de călătorie, Viză de Intraree/Ieșire", "https://www.mae.ro/travel-conditions/3685", "Pentru a călători în Republica Populară Democrată Coreeană este necesară obținerea vizei de intrare/ieșire. Viza se acordă numai pe baza unei invitații oficiale adresate de o instituție sau persoană fizică cu reședința în Coreea de Nord sau la solicitarea scrisă a unei instituții din România. Viza se poate obține de la una dintre ambasadele sau agențiile de turism nord-coreene din străinătate, cu perioada de procesare a vizei de minimum 10 zile. Dată fiind natura extrem de delicată a călătoriilor în acest stat, îți recomandăm să afli mai multe detalii pe site-ul oficial MAE."],
    "Coreea de Sud"
    "Iordania"
    "Emiratele Arabe Unite"
    "Sri Lanka"
    "Bhutan"
    "Taiwan"
    "Israel"
    "Kuweit"
    "Timor-Leste"
    "Qatar"
    "Liban"
    "Brunei"
    "Bahrain"
    "Singapore"
    "Maldive"
    "Palestina"
    "Brazilia"
    "Mexic"
    "Columbia"
    "Argentina"
    "Canada"
    "Peru"
    "Venezuela"
    "Chile"
    "Ecuador"
    "Guatemala"
    "Cuba"
    "Bolivia"
    "Haiti"
    "Republica Dominicană"
    "Honduras"
    "Paraguay"
    "Nicaragua"
    "El Salvador"
    "Costa Rica"
    "Panama"
    "Puerto Rico (Statele Unite ale Americii)"
    "Uruguay"
    "Jamaica"
    "Trinidad Tobago"
    "Guyana"
    "Suriname"
    "Guadeloupe (Franța)"
    "Martinica (Franța)"
    "Bahamas"
    "Belize"
    "Barbados"
    "Guiana Franceză"
    "Sfânta Lucia"
    "Curacao (Regatul Olandei)"
    "Aruba (Regatul Olandei)"
    "Saint Vincent and the Grenadines"
    "Insulele Virgine (Statele Unite ale Americii)"
    "Grenada"
    "Antigua și Barbuda"
    "Dominica"
    "Bermuda (Regatul Unit al Marii Britanii)"
    "Insulele Cayman (Regatul Unit al Marii Britanii)"
    "Groenlanda (Danemarca)"
    "Saint Kitts and Nevis"
    "Sint Marteen (Regatul Olandei)"
    "Turks and Caicos Islands (Regatul Unit al Marii Britanii)"
    "Saint Martin (Franța)"
    "Insulele Virgine Britanice (Regatul Unit al Marii Britanii)"
    "Caribbean Netherlands (Regatul Olandei)"
    "Anguilla (Regatul Unit al Marii Britanii)"
    "Saint Barthelemy (Franța)"
    "Saint Pierre and Miquelon (Franța)"
    "Montserrat (Regatul Unit al Marii Britanii)"
    "Insulele Falkland (Regatul Unit al Marii Britanii)"
    "Australia"
    "Noua Zeelandă"
    "Papua Noua Guinee"
    "Fiji"
    "Insulele Solomon"
    "Vanuatu"
    "Noua Caledonie (Franța)"
    "Polinezia Franceza (Franța)"
    "Samoa"
    "Guam (Statele Unite ale Americii)"
    "Kiribati"
    "Statele Federate ale Microneziei"
    "Tonga"
    "Samoa Americană (Statele Unite ale Americii)"
    "Insulele Mariana de Nord (Statele Unite ale Americii)"
    "Palau"
    "Insulele Cook (Noua Zeelandă)"
    "Wallis and Futuna (Franța)"
    "Tuvalu"
    "Nauru"
    "Insula Norfolk (Australia)
    "Niue (Noua Zeelandă)"
    "Insulele Pitcairn (Regatul Unit al Marii Britanii)"
    "tara naspa" : ["ID, Passport", "https://asasd.com", "Verifică cu autoritățile."],
}

// "country name" : ["papers", "source", "comment"]
// "country name" : "papers"
