{
    "Bulgaria" : "ID, Passport",
    "Cehia" : "ID, Passport",
    "Ungaria" : "ID, Passport",
    "Franta" : "ID, Passport",
    "Germania" : "ID, Passport"
    "Italia" : "ID, Passport"
    "Polonia" : "ID, Passport"
    "Spania" : "ID, Passport"
    "Olanda" : "ID, Passport"
    "Grecia" : "ID, Passport"
    "Croatia" : "ID, Passport"
    "Danemarca" : "ID, Passport"
    "Irlanda" : "ID, Passport"
    "Portugalia" : "ID, Passport"
    "Belgia" : "ID, Passport"
    "Austria" : "ID, Passport"
    "Finlanda" : "ID, Passport"
    "Cipru" : "ID, Passport"
    "Luxemburg" : "ID, Passport"
    "Lituania" : "ID, Passport"
    "Slovenia" : "ID, Passport"
    "Malta" : "ID, Passport"
    "Slovacia" : "ID, Passport"
    "Letonia" : "ID, Passport"
    "Estonia" : "ID, Passport"
    "Suedia" : "ID, Passport"
    "Rusia"
    "Ucraina"
    "Norvegia"
    "Regatul Unit al Marii Britanii"
    "Belarus"
    "Kazakhstan"
    "Islanda"
    "Serbia"
    "Bosnia si Hertegovina"
    "Elvetia"
    "Moldova"
    "Armenia"
    "Albania"
    "Macedonia de Nord"
    "Turcia"
    "Muntenegru"
    "Kosovo"
    "Azerbaijan"
    "Georgia"
    "Andora"
    "Liechtenstein"
    "San Marino"
    "Monaco"
    "Vatican"
    "Statele Unite ale Americii"
    "Nigeria"
    "Etiopia"
    "Egipt"
    "Republica Democrata Congo"
    "Tanzania"
    "Africa de Sud"
    "Kenya"
    "Uganda"
    "Algeria"
    "Sudan"
    "Maroc"
    "Mozambic"
    "Ghana"
    "Angola"
    "Somalia"
    "Coasta de Fildes"
    "Madagascar"
    "Camerun"
    "Burkina Faso"
    "Niger"
    "Malawi"
    "Zambia"
    "Mali"
    "Senegal"
    "Zimbabwe"
    "Ciad"
    "Tunisia"
    "Guinea"
    "Ruanda"
    "Benin"
    "Burundi"
    "Sudanul de Sud"
    "Eritrea"
    "Sierra Leone"
    "Togo"
    "Libia"
    "Republica Centrafricana"
    "Mauritania"
    "Republica Congo"
    "Liberia"
    "Namibia"
    "Botswana"
    "Lesotho"
    "Gambia"
    "Gabon"
    "Guinea-Bissau"
    "Mauritius"
    "Guinea Ecuatoriala"
    "Eswatini"
    "Dijbouti"
    "Reunion (Franta)"
    "Comoros"
    "Capul Verde"
    "Mayotte (Franta)"
    "Sao Tome and Principe"
    "Seychelles"
    "Saint Helena, Ascension and Tristan da Cunha"
    "China"
    "India"
    "Arabia Saudita"
    "Iran"
    "Mongolia"
    "Indonezia"
    "Pakistan"
    "Myanmar"
    "Afghanistan"
    "Yemen"
    "Thailanda"
    "Turkmenistan"
    "Uzbekistan"
    "Irak"
    "Japonia"
    "Vietnam"
    "Malaezia"
    "Oman"
    "Filipine"
    "Laos"
    "Kyrgystan"
    "Siria"
    "Cambodgia"
    "Bangladesh"
    "Nepal"
    "Tajikistan"
    "Coreea de Nord"
    "Coreea de Sud"
    "Iordania"
    "Emiratele Arabe Unite"
    "Sri Lanka"
    "Bhutan"
    "Taiwan"
    "Israel"
    "Kuweit"
    "Timor-Leste"
    "Qatar"
    "Liban"
    "Brunei"
    "Bahrain"
    "Singapore"
    "Maldive"
    "Palestina"
    "Brazilia"
    "Mexic"
    "Columbia"
    "Argentina"
    "Canada"
    "Peru"
    "Venezuela"
    "Chile"
    "Ecuador"
    "Guatemala"
    "Cuba"
    "Bolivia"
    "Haiti"
    "Republica Dominicana"
    "Honduras"
    "Paraguay"
    "Nicaragua"
    "El Salvador"
    "Costa Rica"
    "Panama"
    "Puerto Rico"
    "Uruguay"
    "Jamaica"
    "Trinidad Tobago"
    "Guyana"
    "Suriname"
    "Guadeloupe (Franta)"
    "Martinica (Franta)"
    "Bahamas"
    "Belize"
    "Barbados"
    "Guiana Franceza"
    "Sfanta Lucia"
    "Curacao (Regatul Olandei)"
    "Aruba (Regatul Olandei)"
    "Saint Vincent and the Grenadines"
    "Insulele Virgine (Statele Unite ale Americii)"
    "Grenada"
    "Antigua si Barbuda"
    "Dominica"
    "Bermuda (Regatul Unit al Marii Britanii)"
    "Insulele Cayman (Regatul Unit al Marii Britanii)"
    "Groenlanda (Danemarca)"
    "Saint Kitts and Nevis"
    "Sint Marteen (Regatul Olandei)"
    "Turks and Caicos Islands (Regatul Unit al Marii Britanii)"
    "Saint Martin (Franta)"
    "Insulele Virgine Britanice (Regatul Unit al Marii Britanii)"
    "Caribbean Netherlands (Regatul Olandei)"
    "Anguilla (Regatul Unit al Marii Britanii)"
    "Saint Barthelemy (Franta)"
    "Saint Pierre and Miquelon (Franta)"
    "Montserrat (Regatul Unit al Marii Britanii)"
    "Insulele Falkland (Regatul Unit al Marii Britanii)"
    "Australia"
    "Noua Zeelanda"
    "Papua Noua Guinee"
    "Fiji"
    "Insulele Solomon"
    "Vanuatu"
    "Noua Caledonie (Franta)"
    "Polinezia Franceza (Franta)"
    "Samoa"
    "Guam (Statele Unite ale Americii)"
    "Kiribati"
    "Statele Federate ale Microneziei"
    "Tonga"
    "Samoa Americana (Statele Unite ale Americii)"
    "Insulele Mariana de Nord (Statele Unite ale Americii)"
    "Palau"
    "Insulele Cook (Noua Zeelanda)"
    "Wallis and Futuna (Franta)"
    "Tuvalu"
    "Nauru"
    "Insula Norfolk (Australia)
    "Niue (Noua Zeelanda)"
    "Insulele Pitcairn (Regatul Unit al Marii Britanii)"
    "tara naspa" : ["ID, Passport", "https://asasd.com", "Verifică cu autoritățile."],
}

// "country name" : ["papers", "source", "comment"]
// "country name" : "papers"
